Add Dockerfile.dev for dev environment

diff --git a/console b/console
--- a/console
+++ b/console
@@ -10,11 +10,13 @@ else
     export PYTHONPATH=$PYTHONPATH:$ROOT
 fi
 
-if [ -f $ROOT/virtualenv/bin/activate ]; then
-    . $ROOT/virtualenv/bin/activate
-else
-    echo "error: Missing virtualenv."
-    exit 1
+if [ ! -f /.dockerenv ]; then
+    if [ -f $ROOT/virtualenv/bin/activate ]; then
+        . $ROOT/virtualenv/bin/activate
+    else
+        echo "error: Missing virtualenv."
+        exit 1
+    fi
 fi
 
-python $ROOT/opmuse/commands.py $@
+python3 $ROOT/opmuse/commands.py $@
