run dbconfig stuff in after-remove and before-remove

diff --git a/scripts/debian-after-remove b/scripts/debian-after-remove
--- a/scripts/debian-after-remove
+++ b/scripts/debian-after-remove
@@ -2,5 +2,14 @@
 
 if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
     . /usr/share/debconf/confmodule
+
+    if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
+        . /usr/share/dbconfig-common/dpkg/postrm.mysql
+
+        if ! dbc_go phpmyadmin $@ ; then
+            echo 'Automatic configuration using dbconfig-common failed!'
+        fi
+    fi
+
     db_purge
 fi
diff --git a/scripts/debian-before-remove b/scripts/debian-before-remove
--- a/scripts/debian-before-remove
+++ b/scripts/debian-before-remove
@@ -1,3 +1,10 @@
 #!/bin/sh
 
+. /usr/share/debconf/confmodule
+. /usr/share/dbconfig-common/dpkg/prerm.mysql
+
+if ! dbc_go phpmyadmin $@ ; then
+    echo 'Automatic configuration using dbconfig-common failed!'
+fi
+
 /etc/init.d/opmuse stop
